### ISSUE TITLE
ImportError: cannot import name 'StableCascadeDecoderPipeline' from 'diffusers' (unknown location)

### ISSUE THREAD

**Issue by OhMyGod32** [EtienneDosSantos/stable-cascade-one-click-installer#4]
I have a problem like this:
ImportError: cannot import name 'StableCascadeDecoderPipeline' from 'diffusers' (unknown location)

windows11
I've already tried python3.9 and python3.10

**Comment by EtienneDosSantos** [comment]
> ImportError: cannot import name 'StableCascadeDecoderPipeline' from 'diffusers' (unknown location)

Either the diffusers library is not installed or its installation path is not included in your Python environment.
Could you please check, whether diffusers is installed in the venv following these steps?
1. Open command prompt and navigate to the directory containing the venv: `cd "\path\containing\venv"`
2. `venv\Scripts\activate`
3. `pip install diffusers`

**Comment by Mark4app** [comment]
try :
pip install --force-reinstall --no-deps git+https://github.com/huggingface/diffusers.git@a3dc21385b7386beb3dab3a9845962ede6765887

**Comment by wangwenqiao666** [comment]
I have the same problem
![image](https://github.com/EtienneDosSantos/stable-cascade-one-click-installer/assets/55267900/5bb8c200-488a-4461-a18c-03b0a11a19c2)
![Uploading image.png…]()

**Comment by EtienneDosSantos** [comment]
The problem here is that 'StableCascade*Decoder*Pipeline' does not exist in the Diffusers library. Stable Cascade uses two pipelines: first 'StableCascade*Prior*Pipeline', then follows 'StableCascadePipeline'. This naming convention is indeed quite misleading. 
Could you check in the file 'app.py', whether you're trying to load 'StableCascade*Decoder*Pipeline' instead of 'StableCascadePipeline'?
