### ISSUE TITLE
Model loaded in each generation

### ISSUE THREAD

**Issue by gonewilds** [EtienneDosSantos/stable-cascade-one-click-installer#44]
is this supposed to be like this?

it took an absurd generation time just for 1 image.

i installed locally the huggingface spaces version, it only took ~3-5sec to generate 1 image.

**Comment by IndigoDosSantos** [comment]
That behavior is actually on purpose - it's to keep VRAM usage in check.

About those "absurd generation times" you mentioned - the model loading itself shouldn't really be the culprit here. It can vary with different hardware, sure, but it's usually not the main time-eater.

Just to give you an idea, I ran a quick test on my 4060 Ti 16 GB. Pumping out two 1024x1024 images (batch size of 2) took about 42 seconds. If that sounds close to what you're seeing, then I hate to say it, but that's just how it goes right now 😅

If you're getting way longer times than that, something else might be up. Want to share what kind of setup you're working with?

**Comment by gonewilds** [comment]
i have Nvidia L4 (24Gb Vram) as a main GPU.


i tried this hf spaces and run it locally
https://huggingface.co/spaces/multimodalart/stable-cascade
it took 2-3 sec to generate 1 image.
but compared to yours, it's lack of feature and can only do 1024x1024 or 1024x1536 with only 30+12 Maximum steps 😅. the main difference is each generation didn't load any pipelines component, it loaded only at the beginning.

**Comment by IndigoDosSantos** [comment]
Got it. I've updated the `run.py` file to load models just once. With your GPU VRAM, this should work fine. Replace the `run.py` in the root directory with this [modified file](https://github.com/EtienneDosSantos/stable-cascade-one-click-installer/blob/load-models-once/run.py), and you should see improved performance - no more repeated loading!

**Comment by gonewilds** [comment]
awesome! works like a charm!

thanks for the update 👍
